#!/usr/bin/env python3
"""Write a function that generates a detailed
classification report using Scikit-learn.
    """
from sklearn import metrics


def evaluate(true_labels, predicted_labels, class_names):
    """This report should provide a
Returns:
    A string containing the classification
    report generated by Scikit-learn.
    """
    return metrics.classification_report(
        true_labels,
        predicted_labels,
        target_names=class_names)
